name: Build project
on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
jobs:
  adam:
    name: Initial job
    runs-on: ubuntu-latest
  prebuild:
    name: Prebuild project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run detekt with Gradle Wrapper
        run: ./gradlew detekt
      - name: Run lint with Gradle Wrapper
        run: ./gradlew lint
  build:
    name: Build project
    runs-on: ubuntu-latest
    needs:
      - prebuild
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
  test:
    name: Test project
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run tests with Gradle Wrapper
        run: ./gradlew test
