name: Build project
on:
  pull_request:
    branches:
      - master
env:
  JAVA_VERSION: 17
  JAVA_DISTRIBUTION: temurin
jobs:
  prebuild:
    name: Prebuild project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-cache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-gradle-cache-${{ github.sha }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Run detekt
        run: ./gradlew detekt
  build:
    name: Build project
    runs-on: ubuntu-latest
    needs:
      - prebuild
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-cache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-gradle-cache-${{ github.sha }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
  test:
    name: Test project
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-cache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-gradle-cache-${{ github.sha }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Run tests with Gradle Wrapper
        run: ./gradlew test
